services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
      args:
        - PORT=${PORT:-3000}
    image: mi-app:latest
    env_file:
      - .env
    depends_on:
      - mongo
    environment:
      - PORT=${PORT:-3000}
      - MONGO_URI=${MONGO_URI:-mongodb://mongo:27017/practica-docker}
    ports:
      - "${PORT}:3000"
    networks:
      - api-network

  mongo:
    image: mongo:latest
    volumes:
      - mongo-data:/data/db
    networks:
      - api-network

networks:
  api-network:
    driver: bridge

volumes:
  mongo-data: